version: "3.3"  # optional since v1.27.0
services:
    haproxy:
        image: stadryniak/sms-haproxy
        container_name: "haproxy"
        ports:
            - "24020:24020"
            - "9999:9999"
    sms-postgres:
        image: postgres
        container_name: "postgres"
        ports:
            - "5432:5432"
        environment: 
            - POSTGRES_PASSWORD=sms
            - POSTGRES_USER=sms
            - POSTGRES_DB=sms
        #entrypoint: ["bash", "-c", "psql -U sms -d sms  < db_dump_text"]
    keycloak:
        image: stadryniak/kc-sms
        container_name: "keycloak"
        ports:
            - "24080:8080"
        environment: # WARNING: DO NOT CHANGE
            - DB_ADDR=postgres
            - DB_VENDOR=POSTGRES
            

#    usermanagement-service:
#        image: stadryniak/usermanagement-service
#        ports:
#            - "24034"
#    grades-service:
#        image: stadryniak/grades-service
#        ports:
#            - "24032"
#    homework-service:
#        image: stadryniak/homework-service
#        ports:
#            - "24026"
#    timetable-service:
#        image: stadryniak/timetable-service
#        ports:
#            - "24030"
#    presence-service:
#        image: stadryniak/presence-service
#        ports:
#            - "24028" 